name: Update AltStore Source
run-name: Version ${{ github.event.client_payload.version }}

on:
  repository_dispatch:
    types: [ update-altstore ]

permissions:
  contents: write

jobs:
  update-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Update source
        run: |
          python update_source.py \
            --file apps.json \
            --version ${{ github.event.client_payload.version }} \
            --buildVersion ${{ github.event.client_payload.buildVersion }} \
            --date ${{ github.event.client_payload.date }} \
            --localizedDescription "${{ github.event.client_payload.localizedDescription }}" \
            --downloadURL ${{ github.event.client_payload.downloadURL }} \
            --minOSVersion ${{ github.event.client_payload.minOSVersion }} \
            --size ${{ github.event.client_payload.size }}

      - name: Commit and push changes
        run: |
          git config user.name "actions-user"
          git config user.email "actions-user@users.noreply.github.com"
          git add apps.json
          git commit -m "Version ${{ github.event.client_payload.version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
