name: Update AltStore Source

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
      buildVersion:
        description: "Version code"
        required: true
      date:
        description: "Release date"
        required: true
      localizedDescription:
        description: "Description"
        required: true
      downloadURL:
        description: "Download URL"
        required: true
      minOSVersion:
        description: "Minimum iOS version"
        required: true
      size:
        description: "IPA file size in bytes"
        required: true

permissions:
  contents: write

jobs:
  update-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Update source
        run: |
          python update_source.py \
            --file apps.json \
            --version ${{ github.event.inputs.version }} \
            --buildVersion ${{ github.event.inputs.buildVersion }} \
            --date ${{ github.event.inputs.date }} \
            --localizedDescription "${{ github.event.inputs.localizedDescription }}" \
            --downloadURL ${{ github.event.inputs.downloadURL }} \
            --minOSVersion ${{ github.event.inputs.minOSVersion }} \
            --size ${{ github.event.inputs.size }}

      - name: Commit and push changes
        run: |
          git config user.name "actions-user"
          git config user.email "actions-user@users.noreply.github.com"
          git add apps.json
          git commit -m "Version ${{ github.event.inputs.version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
